version: '3.4'

services:
  enolauncher:
    image: enolauncher:dev
    build:
      target: base
    #environment:
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_enolauncher$
    volumes:
      - C:\Users\Benni\repositories\EnoEngine\EnoLauncher:/app
      - C:\Users\Benni\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_enolauncher$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_enolauncher$ bin/Debug/netcoreapp2.2/EnoLauncher.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
